from .prompts import build_prompt
from .models import FunctionCallResult, FunctionDefinition, TestPrompt
from typing import Any
import json
import re
from functools import lru_cache

try:
    from llm_sdk import Small_LLM_Model as llm_model  # type: ignore
    llm = llm_model()
except KeyboardInterrupt:
    print("Execution interrupted by user (Ctrl+C).")
    exit()
except Exception as e:
    print(f"Unexpected failure - {str(e)}\n")
    exit()

@lru_cache(maxsize=None)
def load_vocab() -> dict[str, int]:
    try :
        with open(llm.get_path_to_vocab_file(), "r") as f:
            vocab: dict[str, int] = json.load(f)
        return vocab
    except FileNotFoundError:
        raise FileNotFoundError("Vocabulary file not found.\n")
    except Exception:
        raise Exception("Invalid vocabulary JSON.\n")


def generate_constrained(
    prompt_ids: list[int],
    allowed_functions: list[str] | None = None,
    stop_char: str | None = None,
) -> str:
    """Generate constrained text based on allowed functions or stop character.

    Args:
        prompt_ids: The initial token sequence representing the prompt.
        allowed_functions: List of valid function names to append.
        stop_char: The character at which text generation should stop.

    Returns:
        The text generated by the model.
    """
    generated_text = ""
    vocab = load_vocab()
    while True:
        logits = llm.get_logits_from_input_ids(prompt_ids)

        if allowed_functions:
            current_typed = generated_text
            valid_ids = [
                t_id
                for t_str, t_id in vocab.items()
                if any(
                    f.startswith(current_typed + t_str)
                    for f in allowed_functions
                )
            ]

            if valid_ids:
                next_token_id = max(valid_ids, key=lambda v_id: logits[v_id])

            else:
                raise ValueError(
                    f"NO Valid Function Start with {llm.decode([prompt_ids])}"
                )
        else:
            next_token_id = logits.index(max(logits))

        word = llm.decode([next_token_id])
        generated_text += word
        prompt_ids.append(next_token_id)
        print(".", end="", flush=True)

        if word is not None and stop_char in word:
            break

    return str(generated_text)


def get_type_parameters(
    functions_definition: list[FunctionDefinition], selected_name: str
) -> dict[str, str]:
    """Retrieve the type of each parameter for a matched function.

    Args:
        functions_definition: A list of function definition models.
        selected_name: The target function name selected by the model.

    Returns:
        A mapping of parameter names to their data types.
    """
    fn_types: dict[str, str] = {}
    for f in functions_definition:
        if selected_name.startswith(f.name):
            for k, t in f.parameters.items():
                fn_types[k] = t.type

    return fn_types


def run_pipeline(
    functions_definition: list[FunctionDefinition], query_prompt: TestPrompt
) -> dict[str, Any] | None:
    """Execute the full function-calling prediction pipeline.

    Args:
        functions_definition: A list of functions the model can choose from.
        query_prompt: The incoming user request to be processed.

    Returns:
        Containing the prompt, function name, and parsed parameters.
    """
    try:
        start_json = (
            f'{{"prompt": {json.dumps(query_prompt.prompt)}, "name": "'
        )
        full_prompt = (
            build_prompt(query_prompt, functions_definition)
            + "\n"
            + start_json
        )
        prompt_ids = llm.encode(full_prompt)[0].tolist()

        fn_names = [f.name + '"' for f in functions_definition]
        selected_name = generate_constrained(
            prompt_ids, allowed_functions=fn_names, stop_char='"'
        )

        suffix = ', "parameters": {"'
        prompt_ids.extend(llm.encode(suffix)[0].tolist())

        params_json = generate_constrained(prompt_ids, stop_char="}")

        type_parameters = get_type_parameters(
            functions_definition, selected_name
        )
        clean_numbers = params_json

        if "number" in type_parameters.values():
            clean_numbers = re.sub(
                r"([:\[,]\s*)(-?\d+)(?![\.\d])", r"\g<1>\g<2>.0", params_json
            )

        full_json_str = start_json + selected_name + suffix + clean_numbers
        try:
            clean_json = re.sub(r'\\(?!["\\bfnrtu])', r"\\\\", full_json_str)
            data = json.loads(clean_json)
            return FunctionCallResult(**data).model_dump()
        except Exception as e:
            raise Exception("Generated output is not valid JSON.\n")

    except KeyboardInterrupt:
        raise KeyboardInterrupt("Execution interrupted by user (Ctrl+C).")
    except ValueError as e:
        raise ValueError(f"\nConstraint Error: {e}")
    except Exception as e:
        raise Exception(f"Unexpected failure - {str(e)}\n")
